name: 'PR Has Issues'
description: 'Checks for issues references in pull requests.'
inputs:
  prefixes:
    description: A comma separated list of key prefixes.
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/ngerakines/pr-has-issues-action:v3'
  args:
    - ${{ inputs.prefixes }}
